title: Chao Shi
description: See yourself through others.
author: Chao Shi & Shangzhi Huang
avatar: /logo.png
email: coshi036@gmail.com & ngzhio@gmail.com

plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate

paginate: 10

# Uncomment the below line and set the tracking ID for enabling Google Analytics
# 
# google_analytics: 

# Uncomment the below lines and set the Disqus shortname for enabling Disqus
# 
# disqus:

# Jekyll
# ======
exclude:
  - scripts/
  - README.md
  - jekyll-theme-hamilton.gemspec

# Jekyll SEO Tag (Optional)
# =========================
twitter:
  username: 
  card: 
logo: logo.png
social:
  name: Chao Shi
  links:
    - https://github.com/ChaoShi036
google_site_verification: u4WXQl0Eu66rsQo2kRdCNx
lang: en
